version: "3.0"
services: 
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command: ["rails", "server", "-b", "0.0.0.0"]
        ports: 
            - 3000:3000
        volumes:
            - .:/appdev
        depends_on: 
            - db
    webpacker:
        build:
            context: .
            dockerfile: Dockerfile
        command: ["./bin/webpack-dev-server"]
        ports: 
            - 3035
        volumes:
            - .:/appdev
        environment: 
            - NODE_ENV=development
            - RAILS_ENV=development
        depends_on: 
            - db
            - app
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports: 
            - 3306
        environment: 
            - MYSQL_ROOT_PASSWORD=Password01
            - MYSQL_DATABASE=galaxy_dev
#         volumes:
#             - galaxy-dev-vol:/var/lib/mysql
# volumes:
#     galaxy-dev-vol:
